### ISSUE TITLE
Error en el texto de descripción de formulario

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#12]
Al entrar a los detalles de un formulario, en la tarjeta de datos de formulario, debería de decir "Descripción de formulario" en vez de "Descripción del evento"

![WhatsApp Image 2023-05-03 at 8 13 40 PM](https://user-images.githubusercontent.com/85699631/236096606-3f2c6686-a429-4b08-8633-b556221d2bda.jpeg)

**Comment by LordSinSentido** [comment]
Corrección realizada en el commit [e4d035f79528358deadf98e2f4590bfcbeb7ed75](https://github.com/SAI-COLOMOS/app-core/commit/e4d035f79528358deadf98e2f4590bfcbeb7ed75) de la rama development
