### ISSUE TITLE
Capitaliza después de cada espacio 

### ISSUE THREAD

**Issue by OwenO-O** [SAI-COLOMOS/app-core#13]
En el apartado de 'Añadir nuevo bosque urbano' el campo 'municipio' capitaliza después de cada espacio.

![Screenshot_20230505-210328_Servicio social](https://user-images.githubusercontent.com/63696633/236595601-3b70e850-f2ec-44ee-a815-4593d109a8da.jpg)

**Comment by LordSinSentido** [comment]
Corrección realizada en el commit [82bc50a1e23d07e0f302deebeff7bb024fe9aed2](https://github.com/SAI-COLOMOS/app-core/commit/82bc50a1e23d07e0f302deebeff7bb024fe9aed2) de la rama development
