### ISSUE TITLE
Admite solo 200 caracteres 

### ISSUE THREAD

**Issue by OwenO-O** [SAI-COLOMOS/app-core#14]
En el apartado 'Añadir nuevo bosque urbano' el campo 'Referencia del lugar' sólo admite 200 caracteres en vez de 500.

![Screenshot_20230505-211302_Servicio social](https://user-images.githubusercontent.com/63696633/236596132-92969ca5-aec5-422d-a2f0-d9beeda33eac.jpg)

**Comment by LordSinSentido** [comment]
Corrección no aplicable, pues el código está programado para aceptar hasta 500 caracteres, se tendría que volver a revisar para corroborar que no sea un error puntual, y en caso de volver a ocurrir reabrir este issue

![Fragmento del código](https://user-images.githubusercontent.com/57022857/236602358-18a56509-8f5e-456e-802a-dfa0424e37a3.png)
