### ISSUE TITLE
'a' fuera de lugar

### ISSUE THREAD

**Issue by OwenO-O** [SAI-COLOMOS/app-core#16]
En el apartado 'Datos del bosque urbano' en la sección de área, el mensaje que muestra cuando no se tiene nada agregado dice <<¿quieres agregar a alguna?>> mostrando una 'a' de más.

.
![Screenshot_20230505-220354_Servicio social](https://user-images.githubusercontent.com/63696633/236598919-ddd10588-da13-415c-848d-53e40dc05234.jpg)

**Comment by LordSinSentido** [comment]
Corrección realidad en el commit [5ecf2c4343ffd766950e44bb3021caf8324555c1](https://github.com/SAI-COLOMOS/app-core/commit/5ecf2c4343ffd766950e44bb3021caf8324555c1)
