### ISSUE TITLE
Ver usuarios que no debería

### ISSUE THREAD

**Issue by OwenO-O** [SAI-COLOMOS/app-core#17]
La cuenta de encargado puede ver los mismos usuarios que un administrador, ya sea otros encargados y hasta el administrador.
Adjunto vídeo.

.
https://user-images.githubusercontent.com/63696633/236601806-0c8fa7d3-967d-4035-98f0-f9430e68d7d4.mp4

**Comment by LordSinSentido** [comment]
¿Seguro que la cuenta con la que accediste tiene el rol de "Encargado"? Por defecto esta sección está oculta para usuarios de tipo "Prestador", incluso la API hace el filtrado mediante una consulta a la base de datos para corroborar que el usuario que mandó la solicitud tenga los permisos necesarios. @JonathanGDiaz

**Comment by LordSinSentido** [comment]
Se revisará el context de la aplicación, con el fin de verificar que se esté vaciando la caché al momento de cerrar sesión

**Comment by LordSinSentido** [comment]
Cambios realizados en el commit [ad2686ecad8ac80aa0fbd43578420336f0c4943d](https://github.com/SAI-COLOMOS/app-core/commit/ad2686ecad8ac80aa0fbd43578420336f0c4943d), en la rama de development, en espera de verificar si el problema fue resuelto
