### ISSUE TITLE
No busca usuarios por correo

### ISSUE THREAD

**Issue by OwenO-O** [SAI-COLOMOS/app-core#18]
Tanto el administrador como el encargado no puede buscar usuarios por su correo; tampoco reconoce el '@'.

.
![Screenshot_20230505-225148_Servicio social](https://user-images.githubusercontent.com/63696633/236600753-3292fe44-a857-4f66-ab14-a59c89f31ac2.jpg)
![Screenshot_20230505-225247_Servicio social](https://user-images.githubusercontent.com/63696633/236600755-93366641-6096-487e-ab4a-d676b1cd4c0f.jpg)
![Screenshot_20230505-225319_Servicio social](https://user-images.githubusercontent.com/63696633/236600756-622aeeed-6b5b-4755-8950-7a51949cc080.jpg)

**Comment by JonathanGDiaz** [comment]
El bug ya está siendo corregido por parte del back-end.

**Comment by LordSinSentido** [comment]
Problema solucionado en el commit [b965718f6b1835f185020bd48f69d0b9c616013e](https://github.com/SAI-COLOMOS/miro-rest/commit/b965718f6b1835f185020bd48f69d0b9c616013e) de la rama test del MIRO-REST, en espera de ser lanzado a producción.
