### ISSUE TITLE
Hora mal asignada al agregar actividades

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#4]
Cuando se agrega una actividad se le pone una hora que no corresponde a la que era cuando se asignó la actividad.

**Comment by LordSinSentido** [comment]
@Saitama18 falta más información para poder replicar el error, hilo cerrado debido a su ambigüedad, sin embargo, se prestará más atención a este modulo.

Favor de volver a abrir un _issue_ citando a este pero con más detalles acerca del bug encontrado.
