### ISSUE TITLE
No se encuentra link de recuperación de contraseña

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#5]
Al momento de solicitar una recuperación de contraseña, manda el correo, pero no el link para cambiar la contraseña, solo el label que dice "Restablece aquí", pero no hay link.

![WhatsApp Image 2023-04-20 at 7 32 44 PM](https://user-images.githubusercontent.com/85699631/233519957-b5532816-b697-4568-b2f9-d0ee000ca5bd.jpeg)

**Comment by LordSinSentido** [comment]
Ya se está revisando y trabajando junto con el equipo de backend para incluir el deep link adecuado para la solución

@JonathanGDiaz

**Comment by JonathanGDiaz** [comment]
Problema solucionado en versiones recientes de la API
