### ISSUE TITLE
Al completar las horas no cambia el estado del prestador

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#6]
Al sobrepasar las horas requeridas el estado del prestador sigue como activo y no pasa a finalizado, la verdad no estoy seguro si esto es un bug o si se debe de asignar el estado de finalizado manualmente.

![WhatsApp Image 2023-04-20 at 8 09 34 PM](https://user-images.githubusercontent.com/85699631/233524226-7815fbe8-fa90-4a8a-b3fd-4bd9852f7541.jpeg)
![WhatsApp Image 2023-04-20 at 8 09 34 PM (1)](https://user-images.githubusercontent.com/85699631/233524252-7aa4c8b8-de94-41aa-bc49-2b7fba3c0cce.jpeg)
![WhatsApp Image 2023-04-20 at 8 09 34 PM (2)](https://user-images.githubusercontent.com/85699631/233524280-a912e049-4e7b-4c19-812f-3a9bebe664ba.jpeg)

**Comment by LordSinSentido** [comment]
Se considera error en la api
Cc @JonathanGDiaz

**Comment by JonathanGDiaz** [comment]
Corregido en versiones superiores de la API.
