### ISSUE TITLE
Problema al agregar un área a un bosque urbano

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#7]
Al querer agregar un área a un bosque le daba al botón aceptar y me cierra la aplicación, entro de nuevo y veo que si me generó el área, solo que me saca de la app. Al entrar a la app y de nuevo intentar agregar un área, me cierra la app y me dice que se ha detenido la aplicación.

Link del video mostrando el problema:
https://drive.google.com/file/d/1zbNxfMeLwaN1SWo-2HFQsETpGiJLOtk3/view?usp=sharing

![WhatsApp Image 2023-04-27 at 2 35 05 PM](https://user-images.githubusercontent.com/85699631/234984767-9690a06d-39af-4288-8802-74e60f74245d.jpeg)

**Comment by LordSinSentido** [comment]
Solucionado a partir de la versión 1.2.1 de la aplicación, este comportamiento ocurría debido a una promesa mal manejada al momento de querer recuperar la información del bosque urbano de manera paralela
