### ISSUE TITLE
No despliega el dropdown de Bosque urbano y de Escuela en los filtros de usuarios

### ISSUE THREAD

**Issue by Saitama18** [SAI-COLOMOS/app-core#8]
Al momento de querer filtrar los usuarios, no despliega el componente dropdown correspondiente a Bosque urbano y al de Escuela, los demás componentes funcionan bien.

Link para ver el error:
https://drive.google.com/file/d/1VwgfLp1tLvwDp73tSnSqYAD3f2CHOYUt/view?usp=sharing

![WhatsApp Image 2023-04-27 at 2 47 09 PM](https://user-images.githubusercontent.com/85699631/234987297-8acad9c8-1bd0-45c5-9d42-df78ee195b7a.jpeg)

**Comment by LordSinSentido** [comment]
Corrección en camino

**Comment by LordSinSentido** [comment]
Corrección realizada en el commit [5ccec9681c6b1246aff9fed19f512c5e8bc189c1](https://github.com/SAI-COLOMOS/app-core/commit/5ccec9681c6b1246aff9fed19f512c5e8bc189c1), de la rama development
